CREATE TABLE `tbl_item_gift` (
  `id` varchar(64) NOT NULL COMMENT 'ID',
  `gift_type` int DEFAULT NULL COMMENT '赠送类型：1-指定用户赠送，2-公开赠送',
  `status` int DEFAULT NULL COMMENT '赠送状态：0-待领取，1-部分领取，2-已领完，3-已撤回，4-已过期',
  `sender_user_id` varchar(64) DEFAULT NULL COMMENT '赠送者用户ID',
  `receiver_user_id` varchar(64) DEFAULT NULL COMMENT '接收者用户ID',
  `item_id` varchar(64) DEFAULT NULL COMMENT '物品ID',
  `ori_id` varchar(64) DEFAULT NULL COMMENT '物品原始ID',
  `total_quantity` int DEFAULT NULL COMMENT '赠送总数量',
  `received_quantity` int DEFAULT NULL COMMENT '已领取数量',
  `gift_code` varchar(32) DEFAULT NULL COMMENT '兑换码',
  `qr_code` text COMMENT '二维码内容',
  `valid_start_time` datetime DEFAULT NULL COMMENT '领取有效期开始时间',
  `valid_end_time` datetime DEFAULT NULL COMMENT '领取有效期结束时间',
  `per_limit` int DEFAULT NULL COMMENT '每人限领数量',
  `remark` varchar(500) DEFAULT NULL COMMENT '赠送备注',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `cancel_time` datetime DEFAULT NULL COMMENT '撤回时间',
  PRIMARY KEY (`id`),
  KEY `idx_sender_user_id` (`sender_user_id`),
  KEY `idx_receiver_user_id` (`receiver_user_id`),
  KEY `idx_gift_code` (`gift_code`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='物品赠送记录';